### ISSUE TITLE
无法隐藏tab bar, 也无法把url框放到顶部

### ISSUE THREAD

**Issue by VictorWinson** [DuktigZhou/FirefoxCustomCSSConfig#1]
无法隐藏tab bar, 也无法把url框放到顶部

![image](https://github.com/DuktigZhou/FirefoxCustomCSSConfig/assets/46397908/c6962e5b-5e40-4420-8df3-ccef795056f5)

Firefox version: Mercury 115.4.0esr

workaround: 
``` css
/* userChrome.css */
#tabbrowser-tabs { visibility: collapse !important; }
```

也尝试了waterfox，结果也类似，请问是userChrome 冲突吗？
